# Spring Security
spring.security.user.name=yash
spring.security.user.password=yash

# Oauth2 Configuration :-
# Google
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=545866029035-bghn7sk2or1k4c8m5sb7roq2rjksvr6f.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Facebook

# GitHub

# Cloudinary Configuration
cloudinary.cloud.name=djksd79en
cloudinary.api.key=198688372366142
cloudinary.api.secret=L-UhUflUT_WjS1tFNliCDGzD3bM

# email configuration
spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=api
spring.mail.password=63632436337a34ad1056cf351776bd0a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
